-- AlterTable
ALTER TABLE "BotConfig" ADD COLUMN "scannerTradingEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "BotConfig" ADD COLUMN "scannerMinRvol" DOUBLE PRECISION NOT NULL DEFAULT 2.0;
ALTER TABLE "BotConfig" ADD COLUMN "scannerMaxFloat" DOUBLE PRECISION NOT NULL DEFAULT 20000000;
ALTER TABLE "BotConfig" ADD COLUMN "scannerMinGapPct" DOUBLE PRECISION NOT NULL DEFAULT 5.0;
ALTER TABLE "BotConfig" ADD COLUMN "scannerTradeSize" DOUBLE PRECISION NOT NULL DEFAULT 75;
ALTER TABLE "BotConfig" ADD COLUMN "scannerCooldownMin" INTEGER NOT NULL DEFAULT 30;
